### ISSUE TITLE
Supporting OpenMetrics

### ISSUE THREAD

**Issue by dmagliola** [prometheus/client_ruby#189]
We should support OpenMetrics. I've started this work in a temporary branch, will start opening PRs.
But this seems to be the master list of things to do.

This is a breaking change that we should release as 3.0.
We should have previous minor versions with deprecation warnings about the things we'll be changing.

## Todo

- Basic Formatting hygiene
  - [ ] Format negotiation with OpenMetrics Accept Header
  - [ ] Add tests to the OpenMetrics formatter I wrote
  - [ ] #EOF
  - [ ] #UNIT including validation / forcing of metric names
      - [ ] ☝️ is a breaking change. Let's first have warnings / nudges in the current versions to get people to rename their metrics

- Timestamps Output
  - [ ] Merge PR #172 which will help with outputting "updated_at" timestamps for time series
  - [ ] Modify stores 
  - [ ] `updated_at` timestamp for each data point
  - [ ] `series_created` series

- [ ] Exemplars

- New Metric types
  - [ ] StateSet
  - [ ] Info

- Document breaking changes (UPGRADING.md)
  - [ ] If you called `Metric#values` or `Stores#all_values`, you'll get objects with timestamps instead of simply float
  - [ ] Naming convention things: You must pass the unit and not include it in the name. You must not add _total to your counters. We'll add both automatically

**Comment by brian-brazil** [comment]
>  is a breaking change.

Adding UNIT should not be breaking. The only big breaking one is _total for counters.

> updated_at timestamp for each data point

I don't see what this has to do with OpenMetrics, and last I checked client_ruby shouldn't need to worry about timestamps at all.

**Comment by dmagliola** [comment]
Ok, wow, that's an impressively quick answer :)

> Adding UNIT should not be breaking. The only big breaking one is _total for counters.

Correct. I'd introduce both together though, since they both imply changing how you name your metrics

> I don't see what this has to do with OpenMetrics, and last I checked client_ruby shouldn't need to worry about timestamps at all.

I interpreted this: 
```
# TYPE foo counter
foo_total 17.0 1520879607.789
```

To be a counter with a value of 17, and a timestamp on when it got updated to that value. Did I misread that?

**Comment by dmagliola** [comment]
@brian-brazil I added a bunch of questions that came up yesterday, trying to implement OpenMetrics in Ruby.
These may stem from me not using very up-to-date documentation, that document I linked to was all I could find.
Could you let me know what's the answer to those? I'd like to work on preparing for this change late in the next couple of week if possible.

Thank you!

**Comment by brian-brazil** [comment]
> Correct. I'd introduce both together though, since they both imply changing how you name your metrics

Unit can be handled gracefully, see how the Python client does it.

> Did I misread that?

You did, it works the exact same as the Prometheus format. Direct instrumentation should never expose timestamps.

**Comment by dmagliola** [comment]
> You did, it works the exact same as the Prometheus format.

I didn't know about these timestamps on the Prometheus format...
What are they for? Do you have any keywords I can google, or links to documentation about them?

Given this:
- Should we report the `_created` series in the Ruby Client, when using OpenMetrics?
- Should exemplars have a timestamp? Or is this also not something the Ruby Client should expose?

**Comment by brian-brazil** [comment]
> What are they for?

Federation roughly speaking, I don't believe client_ruby has the features where they'd come up.

> Should we report the _created series in the Ruby Client, when using OpenMetrics?

Yes, and in Prometheus format too. The same samples should end up in Prometheus no matter what format is negotiated.

> Should exemplars have a timestamp? Or is this also not something the Ruby Client should expose?

If you plan on supporting exemplars, yes.

**Comment by dmagliola** [comment]
Amazing, thank you!

**Comment by jeremiahishere** [comment]
Has there been any movement on this in the last year or two?  I could use this feature and I am happy to take over.

**Comment by dmagliola** [comment]
Hello @jeremiahishere!
Glad to hear you're interested in this feature and would have time to contribute to it!

There hasn't been any movement on this, and there are things we are interested in working on first (mainly, exporting performance), so I don't think this will happen soon.

If you'd like to contribute, we'd love to see that! Depending on how involved this would be, and how much it'd affect the rest of the codebase, it might be worth catching up a bit on a **super basic** draft PR that'd show the general approach, to make sure we're all in the same page, before putting in a lot of work.

**Comment by jeremiahishere** [comment]
I posted a sketch pr to the discussion tab: https://github.com/prometheus/client_ruby/discussions/290
Please take a look when you have some time.
